runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

#handlers:
#- url: /static
#  static_dir: static/

runtime_config:
  python_version: 3.7

manual_scaling:
  instances: 1
resources:
  cpu: 4
  memory_gb: 4.6
  disk_size_gb: 10