# Generated by Django 3.2.12 on 2022-03-22 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('tid', models.CharField(max_length=255, unique=True)),
                ('aggregator_module', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('primary_email', models.CharField(max_length=255)),
                ('secondary_email', models.CharField(max_length=255)),
                ('bcc_email', models.CharField(max_length=255)),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
