# Generated by Django 3.2.12 on 2024-06-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_alter_merchant_bcc_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='bcc_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
